# Generated by Django 3.1.5 on 2021-01-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="test",
        ),
    ]
