# Generated by Django 3.1.5 on 2021-01-18 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_remove_contact_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="address",
            new_name="street",
        ),
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=models.CharField(
                default=datetime.datetime(2021, 1, 18, 16, 27, 34, 599606, tzinfo=utc),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="street_num",
            field=models.CharField(
                default=datetime.datetime(2021, 1, 18, 16, 27, 49, 621975, tzinfo=utc),
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="town",
            field=models.CharField(
                default=datetime.datetime(2021, 1, 18, 16, 27, 55, 462360, tzinfo=utc),
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
