# Generated by Django 3.1.5 on 2021-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_auto_20210118_1727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="vat",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
