# Generated by Django 3.1.5 on 2021-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_auto_20210118_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="vat",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
