# Generated by Django 3.1.5 on 2021-01-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Costumer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("company_description", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("vat_number", models.CharField(max_length=25)),
                ("invoice_email", models.EmailField(max_length=50)),
                ("since", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CostumerContacts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=60)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.costumer",
                    ),
                ),
            ],
        ),
    ]
