# Generated by Django 3.1.5 on 2021-01-12 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_auto_20210112_2017"),
    ]

    operations = [
        migrations.CreateModel(
            name="Klant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firma_naam", models.CharField(max_length=50)),
                ("soort_bedrijf", models.CharField(max_length=100)),
                ("adres", models.CharField(max_length=100)),
                ("btw_nummer", models.CharField(max_length=25)),
                ("factuur_email", models.EmailField(max_length=50)),
                ("sinds", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KlantContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voornaam", models.CharField(max_length=50)),
                ("achternaam", models.CharField(max_length=50)),
                ("tel", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=60)),
                (
                    "klant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="customers.klant",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="costumercontact",
            name="company",
        ),
        migrations.DeleteModel(
            name="Costumer",
        ),
        migrations.DeleteModel(
            name="CostumerContact",
        ),
    ]
