# Generated by Django 3.1.5 on 2021-01-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_auto_20210112_2023"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="KlantContact",
            new_name="Contact",
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name_plural": "Contacten"},
        ),
        migrations.AlterModelOptions(
            name="klant",
            options={"verbose_name_plural": "Klanten"},
        ),
    ]
